### ISSUE TITLE
Cannot set voltage (PXIe-4112)

### ISSUE THREAD

**Issue by wheeller123** [NIVeriStandAdd-Ons/PXIe-411x-Custom-Device#1]
Hi there, I tried using your custom device. Everything is added and configures as expected but when I set the PSU channel 0 to e.g. 12v I can't see any voltage when measuring pins 2 and 3. Any ideas what I might be doing wrong? 

<img width="213" alt="image" src="https://github.com/NIVeriStandAdd-Ons/PXIe-411x-Custom-Device/assets/1076573/68cef2e6-a13e-44bc-b8c6-19046da33fd3">

**Comment by wheeller123** [comment]
Hi @Jimmylvmm, I tried the v1.0.0 release, but I am still not able to set a votage on the PXIe-4112 in Veristand. I am able to set Voltage in Labview when using the device. 

Do you have any suggestions on how I can debug it? Here is how I have it setup
![image](https://github.com/user-attachments/assets/b16a04bc-8a96-44b7-893d-4ab32c25020d)

![image](https://github.com/user-attachments/assets/663bd6fd-3338-4088-9413-36e8312fc637)

![image](https://github.com/user-attachments/assets/ea5fb176-b8a8-4674-a86d-718cce132ec2)

**Comment by Jimmylvmm** [comment]
@wheeller123, could you please share your MAX report with me, including the host PC and RT target? Thank you.

**Comment by wheeller123** [comment]
> @wheeller123, could you please share your MAX report with me, including the host PC and RT target? Thank you.

Thanks for getting back to me. I've uploaded the MAX report here (too big for github attachment)
https://drive.google.com/drive/folders/1-_4JA29MjeSoZxTIym_2QNNsfEchHdjG?usp=drive_link

**Comment by Jimmylvmm** [comment]
On your host PC, VeriStand 2023Q3(23.5) is installed, but on your RT target, VeriStand 23.8 is installed. Please upgrade the VeriStand version to 2023Q4 on the host PC and have a try.
![Capture](https://github.com/user-attachments/assets/f426808c-d2d8-4d3d-b21b-1a6733965048)
![Capture](https://github.com/user-attachments/assets/01ff2d95-84ad-48e9-a950-e7dc852c33e1)

**Comment by Jimmylvmm** [comment]
@wheeller123 I have updated the installer.  Please use the v1.0.0.2. It is validated with a PXIe-4112.

**Comment by Jimmylvmm** [comment]
@wheeller123 Meanwhile, Please choose **Remote** , if you don't connect a sense on the module.
Your configuration：
![Capture](https://github.com/user-attachments/assets/f00c0372-35ae-4054-88ff-a6e9da7bf04e)
My Configuration:
![Capture](https://github.com/user-attachments/assets/3e0ef500-c011-40a7-a2e1-17b850238a62)

**Comment by wheeller123** [comment]
Hi @Jimmylvmm, I updated to 2024 Q4 and set to "Remote" but no changes. I tried to install v.1.0.2 but I get this error even though I've updated NI Package Manager to the latest. Would you be able to commit the latest source code and I will copy it in the custom device folder manaually? 

![image](https://github.com/user-attachments/assets/6f3a3417-a69f-43a9-9c43-2caf1c7e2cd3)

**Comment by wheeller123** [comment]
I was able to extract the Custom Device from the nipkg installer using 7zip and I can see it is working as expected now i.e. I am able to set the Voltage on each channel

![image](https://github.com/user-attachments/assets/237248c4-b76f-4a52-a5e1-b26cd8dbfbc6)

**Comment by Jimmylvmm** [comment]
@wheeller123 Ok. Cheers.
